permissions:
  contents: read
on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: "Check"

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - name: Template flakes check
        run: ./dev/scripts/check-flakes.sh $(find template -name flake.nix)
